site:
  title:  Red Hat Build of Podman Desktop: Installation, Configuration, and Troubleshooting
  start_page: podmandesktop::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
